# Generated by Django 3.2.6 on 2021-08-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_agenda',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
