# Generated by Django 3.2.6 on 2021-08-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='age',
        ),
    ]
