# Generated by Django 3.2.6 on 2021-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_remove_trainer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='email_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
