# Generated by Django 3.2.6 on 2021-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentdetails_laptop_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='email_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
